// <auto-generated />
using System;
using MedicalRep;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalRep.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250511184834_correctseeding")]
    partial class correctseeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicalRep.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Government")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MedicalRep.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pain Relievers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Antibiotics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Antacids"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bronchodilators"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Antihistamines"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Antispasmodics"
                        });
                });

            modelBuilder.Entity("MedicalRep.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Contraindications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosageForm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Indications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrescriptionOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SideEffects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strength")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            CategoryId = 1,
                            Contraindications = "Liver disease, alcohol consumption.",
                            Description = "Used to relieve pain and reduce fever.",
                            DosageForm = "Tablet",
                            ExpiryDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://abclive1.s3.amazonaws.com/2c2edf5e-aa5c-4940-b5c6-6eb1ac32a016/productimage/5099627630375___XL.jpg",
                            Indications = "Used for headaches, body aches, and fever.",
                            Ingredients = "Paracetamol",
                            IsPrescriptionOnly = false,
                            Manufacturer = "Panadol Inc.",
                            Name = "Panadol",
                            Price = 6.00m,
                            Rate = 4.5m,
                            SideEffects = "Nausea, dizziness, stomach upset.",
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = "2",
                            CategoryId = 2,
                            Contraindications = "Allergy to penicillin.",
                            Description = "Antibiotic used to treat bacterial infections.",
                            DosageForm = "Capsule",
                            ExpiryDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://th.bing.com/th/id/OIP.mzw9ErLwuoZUehYkv18gbgHaFX?w=254&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            Indications = "Used for respiratory and urinary tract infections.",
                            Ingredients = "Amoxicillin",
                            IsPrescriptionOnly = true,
                            Manufacturer = "Amoxicillin Ltd.",
                            Name = "Amoxicillin",
                            Price = 12.00m,
                            Rate = 5.0m,
                            SideEffects = "Rash, diarrhea, nausea.",
                            Strength = "250mg"
                        },
                        new
                        {
                            Id = "3",
                            CategoryId = 3,
                            Contraindications = "Kidney disease.",
                            Description = "Antacid used to relieve heartburn and indigestion.",
                            DosageForm = "Chewable Tablet",
                            ExpiryDate = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://th.bing.com/th/id/OIP.k7jkYQfLMGsV5yMr_mG6kwHaHa?w=188&h=188&c=7&r=0&o=5&dpr=1.3&pid=1.7",
                            Indications = "Relieves heartburn, acid indigestion, and upset stomach.",
                            Ingredients = "Calcium Carbonate",
                            IsPrescriptionOnly = false,
                            Manufacturer = "Tums Inc.",
                            Name = "Tums",
                            Price = 3.50m,
                            Rate = 4.0m,
                            SideEffects = "Constipation, nausea.",
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = "4",
                            CategoryId = 2,
                            Contraindications = "Hypersensitivity to cephalosporins.",
                            Description = "Third-generation cephalosporin antibiotic for serious infections.",
                            DosageForm = "Injection",
                            ExpiryDate = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://th.bing.com/th/id/OIP.yu5HYMc0tyh-yWebIPCldgAAAA?cb=iwc2&rs=1&pid=ImgDetMain",
                            Indications = "Severe bacterial infections, meningitis, pneumonia.",
                            Ingredients = "Ceftriaxone sodium",
                            IsPrescriptionOnly = true,
                            Manufacturer = "Roche",
                            Name = "Ceftriaxone (Rocephin)",
                            Price = 85.00m,
                            Rate = 4.7m,
                            SideEffects = "Diarrhea, rash, pain at injection site.",
                            Strength = "1g/vial"
                        },
                        new
                        {
                            Id = "5",
                            CategoryId = 1,
                            Contraindications = "Severe liver impairment.",
                            Description = "Egyptian paracetamol for pain and fever relief.",
                            DosageForm = "Tablet",
                            ExpiryDate = new DateTime(2026, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://th.bing.com/th/id/OIP.mkMq7pl1TZqmgElVI1MgmwHaHa?cb=iwc2&rs=1&pid=ImgDetMain",
                            Indications = "Headache, fever, mild to moderate pain.",
                            Ingredients = "Paracetamol",
                            IsPrescriptionOnly = false,
                            Manufacturer = "EIPICO",
                            Name = "Adol (Paracetamol)",
                            Price = 8.00m,
                            Rate = 4.2m,
                            SideEffects = "Rare at therapeutic doses.",
                            Strength = "500mg"
                        },
                        new
                        {
                            Id = "6",
                            CategoryId = 3,
                            Contraindications = "GI hemorrhage, mechanical obstruction.",
                            Description = "For nausea, vomiting, bloating and heartburn.",
                            DosageForm = "Tablet",
                            ExpiryDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://th.bing.com/th/id/OIP.inCIZfWjCvKuX6NslxK66gHaHa?cb=iwc2&rs=1&pid=ImgDetMain",
                            Indications = "Gastric motility disorders, nausea, vomiting.",
                            Ingredients = "Domperidone maleate",
                            IsPrescriptionOnly = false,
                            Manufacturer = "Misr Pharma",
                            Name = "Digest (Domperidone)",
                            Price = 12.50m,
                            Rate = 4.3m,
                            SideEffects = "Dry mouth, headache, diarrhea.",
                            Strength = "10mg"
                        },
                        new
                        {
                            Id = "7",
                            CategoryId = 2,
                            Contraindications = "Pregnancy, severe coronary artery disease.",
                            Description = "Improves cerebral circulation and cognitive function.",
                            DosageForm = "Tablet",
                            ExpiryDate = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://cdn.youmed.vn/tin-tuc/wp-content/uploads/2020/04/thuoc-cavinton-5mg.jpg",
                            Indications = "Cerebrovascular disorders, memory impairment.",
                            Ingredients = "Vinpocetine",
                            IsPrescriptionOnly = true,
                            Manufacturer = "Gulf Pharmaceutical Industries",
                            Name = "Cavinton (Vinpocetine)",
                            Price = 45.00m,
                            Rate = 4.4m,
                            SideEffects = "Dizziness, nausea, sleep disturbances.",
                            Strength = "5mg"
                        },
                        new
                        {
                            Id = "8",
                            CategoryId = 3,
                            Contraindications = "Concomitant use with rilpivirine.",
                            Description = "Proton pump inhibitor for acid-related disorders.",
                            DosageForm = "Capsule",
                            ExpiryDate = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://prospecte.ro/images/omez-20-mg-omeprazol-caps-gastrorez.jpg",
                            Indications = "GERD, peptic ulcers, Zollinger-Ellison syndrome.",
                            Ingredients = "Omeprazole",
                            IsPrescriptionOnly = false,
                            Manufacturer = "Dr. Reddy's",
                            Name = "Omez (Omeprazole)",
                            Price = 35.00m,
                            Rate = 4.6m,
                            SideEffects = "Headache, diarrhea, abdominal pain.",
                            Strength = "20mg"
                        },
                        new
                        {
                            Id = "9",
                            CategoryId = 1,
                            Contraindications = "Acute intoxication, MAOI use.",
                            Description = "Opioid analgesic for moderate to severe pain.",
                            DosageForm = "Capsule",
                            ExpiryDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://th.bing.com/th/id/R.8952c303f57ef1212b064cd84f03ce03?rik=0TC1X2cQDWe3ZQ&pid=ImgRaw&r=0",
                            Indications = "Moderate to severe pain management.",
                            Ingredients = "Tramadol hydrochloride",
                            IsPrescriptionOnly = true,
                            Manufacturer = "Minapharm",
                            Name = "Tramal (Tramadol)",
                            Price = 55.00m,
                            Rate = 4.1m,
                            SideEffects = "Nausea, dizziness, constipation.",
                            Strength = "50mg"
                        },
                        new
                        {
                            Id = "10",
                            CategoryId = 1,
                            Contraindications = "Acute heart failure, cardiogenic shock.",
                            Description = "Beta-blocker for hypertension and heart conditions.",
                            DosageForm = "Tablet",
                            ExpiryDate = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://th.bing.com/th/id/OIP.B_Q0EkQC8jh5KjK0ndGYcwHaHG?w=193&h=185&c=7&r=0&o=5&cb=iwc2&dpr=1.3&pid=1.7",
                            Indications = "Hypertension, angina, heart failure.",
                            Ingredients = "Metoprolol tartrate",
                            IsPrescriptionOnly = true,
                            Manufacturer = "Novartis",
                            Name = "Betaloc (Metoprolol)",
                            Price = 40.00m,
                            Rate = 4.5m,
                            SideEffects = "Fatigue, dizziness, bradycardia.",
                            Strength = "50mg"
                        });
                });

            modelBuilder.Entity("MedicalRep.Models.ProductSpecialization", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "SpecializationId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("ProductSpecializations");

                    b.HasData(
                        new
                        {
                            ProductId = "1",
                            SpecializationId = 1
                        },
                        new
                        {
                            ProductId = "1",
                            SpecializationId = 2
                        },
                        new
                        {
                            ProductId = "1",
                            SpecializationId = 4
                        },
                        new
                        {
                            ProductId = "2",
                            SpecializationId = 3
                        },
                        new
                        {
                            ProductId = "2",
                            SpecializationId = 7
                        },
                        new
                        {
                            ProductId = "2",
                            SpecializationId = 10
                        },
                        new
                        {
                            ProductId = "3",
                            SpecializationId = 7
                        },
                        new
                        {
                            ProductId = "3",
                            SpecializationId = 8
                        },
                        new
                        {
                            ProductId = "4",
                            SpecializationId = 3
                        },
                        new
                        {
                            ProductId = "4",
                            SpecializationId = 7
                        },
                        new
                        {
                            ProductId = "4",
                            SpecializationId = 10
                        },
                        new
                        {
                            ProductId = "5",
                            SpecializationId = 1
                        },
                        new
                        {
                            ProductId = "5",
                            SpecializationId = 2
                        },
                        new
                        {
                            ProductId = "5",
                            SpecializationId = 4
                        },
                        new
                        {
                            ProductId = "6",
                            SpecializationId = 7
                        },
                        new
                        {
                            ProductId = "7",
                            SpecializationId = 2
                        },
                        new
                        {
                            ProductId = "7",
                            SpecializationId = 6
                        },
                        new
                        {
                            ProductId = "8",
                            SpecializationId = 7
                        },
                        new
                        {
                            ProductId = "9",
                            SpecializationId = 1
                        },
                        new
                        {
                            ProductId = "9",
                            SpecializationId = 4
                        },
                        new
                        {
                            ProductId = "10",
                            SpecializationId = 1
                        });
                });

            modelBuilder.Entity("MedicalRep.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("MedicalRep.Models.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Specializations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Specialized in heart diseases and conditions.",
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Specialized in brain and nervous system disorders.",
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Specialized in the care of infants, children, and adolescents.",
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Specialized in musculoskeletal conditions.",
                            Name = "Orthopedics"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Specialized in skin, hair, and nail conditions.",
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Specialized in mental health and emotional disorders.",
                            Name = "Psychiatry"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Specialized in the digestive system and its disorders.",
                            Name = "Gastroenterology"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Specialized in female reproductive health.",
                            Name = "Gynecology"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Specialized in eye conditions and surgery.",
                            Name = "Ophthalmology"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Specialized in urinary tract and male reproductive organs.",
                            Name = "Urology"
                        });
                });

            modelBuilder.Entity("MedicalRep.Models.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualVisitDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalRepId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MedicalRepId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("MedicalRep.Models.ApplicationUser", b =>
                {
                    b.HasOne("MedicalRep.Models.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("MedicalRep.Models.Product", b =>
                {
                    b.HasOne("MedicalRep.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MedicalRep.Models.ProductSpecialization", b =>
                {
                    b.HasOne("MedicalRep.Models.Product", "Product")
                        .WithMany("ProductSpecializations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalRep.Models.Specialization", "Specialization")
                        .WithMany("ProductSpecializations")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("MedicalRep.Models.Review", b =>
                {
                    b.HasOne("MedicalRep.Models.ApplicationUser", "Doctor")
                        .WithMany("Reviews")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalRep.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MedicalRep.Models.Visit", b =>
                {
                    b.HasOne("MedicalRep.Models.ApplicationUser", "Doctor")
                        .WithMany("DoctorVisits")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalRep.Models.ApplicationUser", "MedicalRep")
                        .WithMany("MedicalRepVisits")
                        .HasForeignKey("MedicalRepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("MedicalRep");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MedicalRep.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MedicalRep.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalRep.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MedicalRep.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalRep.Models.ApplicationUser", b =>
                {
                    b.Navigation("DoctorVisits");

                    b.Navigation("MedicalRepVisits");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MedicalRep.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MedicalRep.Models.Product", b =>
                {
                    b.Navigation("ProductSpecializations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MedicalRep.Models.Specialization", b =>
                {
                    b.Navigation("Doctors");

                    b.Navigation("ProductSpecializations");
                });
#pragma warning restore 612, 618
        }
    }
}
